### ISSUE TITLE
Flipper-Zero-Port

### ISSUE THREAD

**Issue by arag0re** [stacksmashing/tamarin-firmware#10]
# Flipper-Zero-Port
Hey, i was thinking about porting the project for the flipper-zero.
Was wondering if anyone here is interested in the idea or maybe even started already.
Lemme know if u know something.

**Comment by arag0re** [comment]
https://yuricable.pro
https://github.com/arag0re/fz-yuricable-pro-max

**Comment by nezza** [comment]
Nice work! Thanks for sharing! Closing this for now :)
