### ISSUE TITLE
TamarinCable on PiZero2WH??

### ISSUE THREAD

**Issue by maroc46** [stacksmashing/tamarin-firmware#21]
Hey i have a question about the Tamarin-Firmware 

Is there a way to work the TamarinCable on a pi zero 2 with headers ? 

It's have the Pi3 Chip 
Allows for otg 
And I think when someone have a piZero2 thats is good way to use this and use it for multiple prozess 

I have an Windows Maschine and onder my piZero is a kali machine 
It were super nice to use the pi zero as a linux box out from windows over ssh in the otg mode

**Comment by nezza** [comment]
You would have to significantly rewrite it - the Pi Zero 2 works very differently from the Pico in terms of how you interface with the IOs.

Not meant to discourage, but it won't be a simple change I think :)
