### ISSUE TITLE
USB Data when using DFU

### ISSUE THREAD

**Issue by cr0bar** [stacksmashing/tamarin-firmware#3]
Is there any way to use USB data on the 2 spare wires along side DFU?

I’ve tried wiring it up to a chopped up USB cable (using just the data lines) but had no success, assume it’s not that simple.

**Comment by nezza** [comment]
You should be able to, however I believe there is another authentication step involved that requires a Lightning-Cable serial number

**Comment by blueapple49** [comment]
Rx tx card is reading an address i2c at the test point but this cable is read directly via usb 👍 I will use my project if you allow it there will be a big box uatt reading i2c rffe all protocol read

**Comment by CarloMara** [comment]
@blueapple49 Hey bud, not sure I get your comment. Can you explain a bit more?

**Comment by blueapple49** [comment]
Are you read this cable i2c line and map adresses and which protocol read this cable.i2c can be read pinout with rx tx if use this cable read with usb

**Comment by nezza** [comment]
Heya,
Can you try to re-phrase?

I2C does not have "RX & TX", and not sure which I2C line you mean. If you mean the iPhone internal I2C bus that lets the processor communicate with the Tristar: I don't think that is exposed on Lightning, but can be handled on the hots side.

**Comment by nezza** [comment]
(Also, it's not relevant to this issue, so please create a separate one)

**Comment by blueapple49** [comment]
Thank you for answer
