### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by hilham1990** [stacksmashing/tamarin-firmware#6]
hello how to download Raspberry Pico software can you please help

**Comment by nezza** [comment]
As the issue does not actually describe any issue I'm closing it.

**Comment by nezza** [comment]
@CarloMara

**Comment by CarloMara** [comment]
Hey buddy,

I suggest you give a read on the official raspberry pico sdk [here](https://raspberrypi.github.io/pico-sdk-doxygen/), everything will be much clearer after.

Also, worth noting, this is not an easy beginner project so if you are not familiar with the tools I suggest trying out some tutorials first to familiarize with the tools.

Cheers,
Carlo

**Comment by hilham1990** [comment]
![Uploading 38EDF8B0-D275-4C87-BDA7-14E91AB76389.jpeg…]()

**Comment by hilham1990** [comment]
![Uploading 35336AD5-52D2-422B-8109-0C9870AE7C0A.jpeg…]()

**Comment by CarloMara** [comment]
I'm not entirely sure you uploaded what you think you did

**Comment by CarloMara** [comment]
Two things:

1. I strongly suggest to not upload pictures, but rather copy and paste the text of any error messages. This will enable indexing/searching and can help other users, and it's easier to understand for maintainers,
2. A simple google search for any of the variable names in the error message will point you in the right direction, you have to properly configure the Raspberry Pico SDK. I suggest you try googling for `PICO_SDK_PATH`. 

I think [this](https://blog.smittytone.net/2021/02/02/program-raspberry-pi-pico-c-mac/) might help you out, but I'm not able to help you further debug your setup. 

I'll close this issue as it's not related to our project. If you have issues with the Tamarin code itself feel free to open another PR

**Comment by hilham1990** [comment]
new in software, i tired you so much from it, thank you

**Comment by nezza** [comment]
> I'm tired of you

You probably want to look at how you communicate with people who try to help you (without getting anything in return).
